[package]
name = "AOI_log_file"
version = "0.1.2"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
chrono = "0.4.40"
env_logger = "0.11.6"
log = "0.4.26"
roxmltree = "0.20.0"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"
