[package]
name = "ICT_auth_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0"
egui = "0"
env_logger = "0"
anyhow = "1"
egui_extras = "0.27.2"

ICT_auth = { path = "..\\auth" }